backend:
  name: git-gateway
  branch: cms-posts

publish_mode: editorial_workflow
media_folder: "images/portfolio"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Publish Date", name: "project-date", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Id", name: "modal-id", widget: "number"}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
